config/routes.rb
Rails.application.routes.draw do

  resources :lists

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.create(name: params[:list][:name])
    render :show
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update_attributes(name: params[:list][:name])
    render :show
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails28Jan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
      <div class="col-md-12">
        <%= link_to "home", lists_path, {class: ["btn", "btn-default"]} %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#delete</h1>
<p>Find me in app/views/lists/delete.html.erb</p>

app/views/lists/edit.html.erb
    <h1> edit </h1>
    <%= form_for(@list) do |f| %>
      <%= f.label "Name", :name %>
      <%= f.text_field :name %>
      <%= f.submit %>
    <% end %>

app/views/lists/index.html.erb
<h1>All lists</h1>

<ol>
<% @lists.each do |list| %>
  <li><%= link_to list.name, list %></li>
<% end %>
</ol>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

<%= form_for(@list) do |f| %>
  <%= f.label "Name", :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1> showing </h1>

<h3>name:</h3> <%= @list.name %>

<%= link_to "edit", edit_list_path(@list.id) %>